services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    env_file: ".env"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${URL}
      - VALIDATION=http
      #- SUBDOMAINS=www, #optional
      #- CERTPROVIDER= # optional, default is Lets Encrypt
      #- DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      #- EMAIL= #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      #- STAGING=false #optional
      #- DISABLE_F2B= #optional
      #- SWAG_AUTORELOAD=true
      #- SWAG_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - ./conf/swag/conf:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  postfix:
    env_file:
      - ".env"
    build:
      context: /services/smtp 
    depends_on:
      - swag
    container_name: postfix-smtp
    volumes:
      - ./conf/swag/conf/etc/letsencrypt/live/${URL}:/etc/postfix/tls:ro
      - ./conf/postfix/conf/:/etc/postfix # Postfix config files
      - ./conf/postfix/spool:/var/spool/postfix # Mail queue
    ports:
      - "25:25"
      - "587:587"
      # - "465:465" # If you need SMTPS
    restart: unless-stopped

  dovecot:
    env_file:
        - ".env"
    build: 
      context: /services/imap
    container_name: dovecot-imap
    volumes:
      - ./conf/swag/conf/etc/letsencrypt/live/${URL}:/etc/dovecot/tls:ro
      - ./conf/dovecot/conf/:/etc/dovecot/
    ports:
      - "143:143"
      - "993:993"
    restart: unless-stopped