services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    networks:
      - mail_network
    container_name: swag
    env_file: ".env"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${URL}
      - VALIDATION=http
      #- SUBDOMAINS=www, #optional
      #- CERTPROVIDER= # optional, default is Lets Encrypt
      #- DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      #- EMAIL= #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      - STAGING=true #optional
      #- DISABLE_F2B= #optional
      - SWAG_AUTORELOAD=true
      #- SWAG_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - ./conf/swag/config:/config
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    healthcheck:
      test: ["CMD-SHELL", "test -f /config/etc/letsencrypt/live/${URL}/privkey.pem"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  postfix:
    container_name: "postfix-smtp"
    env_file:
      - ".env"
    build:
      context: smtp/
    depends_on:
      swag:
          condition: service_healthy
          restart: true
    volumes:
      - ./conf/swag/config/etc/:/le-ssl:ro
      - ./smtp/conf/master.cf:/etc/postfix/master.cf
      - ./conf/postfix/spool:/var/spool/postfix 
    ports:
      - "25:25"
      - "587:587"
    restart: unless-stopped
    networks:
    - mail_network

  dovecot:
    env_file:
        - ".env"
    build:
      context: imap/
    depends_on:
      swag:
        condition: service_healthy
    container_name: dovecot-imap
    volumes:
      - ./conf/swag/config/etc/:/le-ssl:ro
      - ./imap/conf/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./imap/conf/users:/etc/dovecot/users
      - ./conf/postfix/spool:/var/spool/postfix 
    ports:
      - "143:143"
      - "993:993"
    restart: unless-stopped
    networks:
    - mail_network

networks:
  mail_network:
    driver: bridge