services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    networks:
      - mail_network
    container_name: swag
    env_file: ".env"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${URL}
      - VALIDATION=http
      #- SUBDOMAINS=www, #optional
      #- CERTPROVIDER= # optional, default is Lets Encrypt
      #- DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      #- EMAIL= #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      - STAGING=true #optional
      #- DISABLE_F2B= #optional
      - SWAG_AUTORELOAD=true
      #- SWAG_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - ./conf/swag/config:/config
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    healthcheck:
      test:
        ["CMD-SHELL", "test -f /config/etc/letsencrypt/live/${URL}/privkey.pem"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
