services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    networks:
      - mail_network
    container_name: swag
    env_file: ".env"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${URL}
      - VALIDATION=http
      #- SUBDOMAINS=www, #optional
      #- CERTPROVIDER= # optional, default is Lets Encrypt
      #- DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      #- EMAIL= #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      - STAGING=true #optional
      #- DISABLE_F2B= #optional
      - SWAG_AUTORELOAD=true
      #- SWAG_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - ./conf/swag/config:/config
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    healthcheck:
      test: [ "CMD-SHELL", "test -f /config/etc/letsencrypt/live/${URL}/privkey.pem" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  # MILTERS
  rspamd:
    image: rspamd/rspamd:latest
    container_name: rspamd
    ports:
      - "11332:11332"  # Proxy worker
      - "11334:11334"  # Web interface
    volumes:
      - /spam/conf/local.d:/etc/rspamd/local.d
      - /spam/conf/data:/var/lib/rspamd
      - /spam/conf/logs:/var/log/rspamd
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mail_network

  redis:
    image: redis:alpine
    container_name: rspamd-redis
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - mail_network

  # valkey:
  #   container_name: valkey
  #   image: valkey:8.1.3-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./valkey/data:/data

  opendkim:
    container_name: "opendkim"
    depends_on:
      swag:
        condition: service_healthy
        restart: true
    build:
      context: opendkim/
    env_file:
      - ".env"
    ports:
      - "8891:8891"
    volumes:
      - ./opendkim/conf/opendkim.conf:/etc/opendkim.conf
      - ./opendkim/keys:/etc/opendkim/keys:rw
    restart: unless-stopped
    networks:
      - mail_network

  # MAIL SERVER COMPONENTS
  postfix:
    container_name: "postfix-smtp"
    env_file:
      - ".env"
    build:
      context: smtp/
    depends_on:
      swag:
        condition: service_healthy
        restart: true
    volumes:
      - ./conf/swag/config/etc/:/le-ssl:ro
      - ./smtp/conf/master.cf:/etc/postfix/master.cf
      - ./conf/postfix/spool:/var/spool/postfix
    ports:
      - "25:25"
      - "587:587"
    restart: unless-stopped
    networks:
      - mail_network

  dovecot:
    container_name: dovecot-imap
    build:
      context: imap/
    env_file:
      - ".env"
    depends_on:
      swag:
        condition: service_healthy
    volumes:
      - ./conf/swag/config/etc/:/le-ssl:ro
      - ./imap/conf/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./imap/conf/dovecot-oauth2.conf.ext:/etc/dovecot/dovecot-oauth2.conf.ext
      - ./imap/conf/users:/etc/dovecot/users
      - ./conf/postfix/spool:/var/spool/postfix
    ports:
      - "143:143"
      - "993:993"
    restart: unless-stopped
    networks:
      - mail_network

# NETWORK & MOUNTS
networks:
  mail_network:
    driver: bridge

volumes:
    redis-data: